const InstagramData =  [
    {
        type:"fashion",
        img: '/assets/images/insta/1.jpg',
    },
    {
        type:"fashion",
        img: '/assets/images/insta/3.jpg',
    },
    {
        type:"fashion",
        img: '/assets/images/insta/5.jpg',
    },
    {
        type:"fashion",
        img: '/assets/images/insta/7.jpg',
    },
    {
        type:"fashion",
        img: '/assets/images/insta/9.jpg',
    },
    {
        type:"fashion",
        img: '/assets/images/insta/11.jpg',
    },
    {
        type:"fashion",
        img: '/assets/images/insta/13.jpg',
    },
    {
        type:"fashion",
        img: '/assets/images/insta/2.jpg',
    },
    {
        type:"kids",
        img: '/assets/images/slider/kids/2.jpg',
    },
    {
        type:"kids",
        img: '/assets/images/slider/kids/3.jpg',
    },
    {
        type:"kids",
        img: '/assets/images/slider/kids/4.jpg',
    },
    {
        type:"kids",
        img: '/assets/images/slider/kids/9.jpg',
    },
    {
        type:"kids",
        img: '/assets/images/slider/kids/6.jpg',
    },
    {
        type:"kids",
        img: '/assets/images/slider/kids/7.jpg',
    },
    {
        type:"kids",
        img: '/assets/images/slider/kids/8.jpg',
    },
    {
        type:"kids",
        img: '/assets/images/slider/kids/1.jpg',
    },
    {
        type:"beauty",
        img:"/assets/images/slider/beauty/3.jpg"
    },
    {
        type:"beauty",
        img:"/assets/images/slider/beauty/2.jpg"
    },
    {
        type:"beauty",
        img:"/assets/images/slider/beauty/6.jpg"
    },
    {
        type:"beauty",
        img:"/assets/images/slider/beauty/7.jpg"
    },
    {
        type:"beauty",
        img:"/assets/images/slider/beauty/4.jpg"
    },
    {
        type:"beauty",
        img:"/assets/images/slider/beauty/5.jpg"
    },
    {
        type:"beauty",
        img:"/assets/images/slider/beauty/2.jpg"
    },
    {
        type:"jewellery",
        img:"/assets/images/slider/jewellery/1.jpg"
    },
    {
        type:"jewellery",
        img:"/assets/images/slider/jewellery/2.jpg"
    },
    {
        type:"jewellery",
        img:"/assets/images/slider/jewellery/3.jpg"
    },
    {
        type:"jewellery",
        img:"/assets/images/slider/jewellery/4.jpg"
    },
    {
        type:"jewellery",
        img:"/assets/images/slider/jewellery/5.jpg"
    },
    {
        type:"jewellery",
        img:"/assets/images/slider/jewellery/6.jpg"
    },
    {
        type:"jewellery",
        img:"/assets/images/slider/jewellery/7.jpg"
    },
    {
        type:"nursery",
        img:"/assets/images/slider/nursery/1.jpg"
    },
    {
        type:"nursery",
        img:"/assets/images/slider/nursery/2.jpg"
    },
    {
        type:"nursery",
        img:"/assets/images/slider/nursery/3.jpg"
    },
    {
        type:"nursery",
        img:"/assets/images/slider/nursery/4.jpg"
    },
    {
        type:"nursery",
        img:"/assets/images/slider/nursery/5.jpg"
    },
    {
        type:"nursery",
        img:"/assets/images/slider/nursery/6.jpg"
    },
    {
        type:"nursery",
        img:"/assets/images/slider/nursery/7.jpg"
    },
    {
        type:"nursery",
        img:"/assets/images/slider/nursery/8.jpg"
    },
    {
        type:"nursery",
        img:"/assets/images/slider/nursery/9.jpg"
    },
    {
        type:"goggles",
        img:"/assets/images/slider/goggles/1.jpg"
    },
    {
        type:"goggles",
        img:"/assets/images/slider/goggles/2.jpg"
    },
    {
        type:"goggles",
        img:"/assets/images/slider/goggles/3.jpg"
    },
    {
        type:"goggles",
        img:"/assets/images/slider/goggles/4.jpg"
    },
    {
        type:"goggles",
        img:"/assets/images/slider/goggles/5.jpg"
    },
    {
        type:"goggles",
        img:"/assets/images/slider/goggles/6.jpg"
    },
    {
        type:"goggles",
        img:"/assets/images/slider/goggles/7.jpg"
    },
    {
        type:"goggles",
        img:"/assets/images/slider/goggles/8.jpg"
    },
    {
        type:"shoes",
        img:"/assets/images/slider/shoes/1.jpg"
    },
    {
        type:"shoes",
        img:"/assets/images/slider/shoes/2.jpg"
    },
    {
        type:"shoes",
        img:"/assets/images/slider/shoes/3.jpg"
    },
    {
        type:"shoes",
        img:"/assets/images/slider/shoes/4.jpg"
    },
    {
        type:"shoes",
        img:"/assets/images/slider/shoes/5.jpg"
    },
    {
        type:"shoes",
        img:"/assets/images/slider/shoes/6.jpg"
    },
    {
        type:"shoes",
        img:"/assets/images/slider/shoes/7.jpg"
    },
    {
        type:"shoes",
        img:"/assets/images/slider/shoes/8.jpg"
    },
    {
        type:"shoes",
        img:"/assets/images/slider/shoes/9.jpg"
    },
    {
        type:"shoes",
        img:"/assets/images/slider/shoes/10.jpg"
    },
    {
        type:"gym",
        img:"/assets/images/slider/gym/1.jpg"
    },
    {
        type:"gym",
        img:"/assets/images/slider/gym/2.jpg"
    },
    {
        type:"gym",
        img:"/assets/images/slider/gym/3.jpg"
    },
    {
        type:"gym",
        img:"/assets/images/slider/gym/4.jpg"
    },
    {
        type:"gym",
        img:"/assets/images/slider/gym/5.jpg"
    },
    {
        type:"gym",
        img:"/assets/images/slider/gym/6.jpg"
    },
    {
        type:"gym",
        img:"/assets/images/slider/gym/7.jpg"
    },
    {
        type:"videoSlider",
        img:"/assets/images/slider/fashion/2.jpg"
    },
    {
        type:"videoSlider",
        img:"/assets/images/slider/fashion/1.jpg"
    },
    {
        type:"videoSlider",
        img:"/assets/images/slider/fashion/3.jpg"
    },
    {
        type:"videoSlider",
        img:"/assets/images/slider/fashion/4.jpg"
    },
    {
        type:"videoSlider",
        img:"/assets/images/slider/fashion/5.jpg"
    },
    {
        type:"videoSlider",
        img:"/assets/images/slider/fashion/6.jpg"
    },
    {
        type:"videoSlider",
        img:"/assets/images/slider/fashion/7.jpg"
    },
    {
        type:"videoSlider",
        img:"/assets/images/slider/fashion/8.jpg"
    },
    {
        type:"videoSlider",
        img:"/assets/images/slider/fashion/9.jpg"
    },
    {
        type:"videoSlider",
        img:"/assets/images/slider/fashion/10.jpg"
    },
    {
        type:"videoSlider",
        img:"/assets/images/slider/fashion/11.jpg"
    },
    {
        type:"bags",
        img:"/assets/images/slider/bags/1.jpg"
    },
    {
        type:"bags",
        img:"/assets/images/slider/bags/2.jpg"
    },
    {
        type:"bags",
        img:"/assets/images/slider/bags/3.jpg"
    },
    {
        type:"bags",
        img:"/assets/images/slider/bags/4.jpg"
    },
    {
        type:"bags",
        img:"/assets/images/slider/bags/5.jpg"
    },
    {
        type:"bags",
        img:"/assets/images/slider/bags/6.jpg"
    },
    {
        type:"bags",
        img:"/assets/images/slider/bags/7.jpg"
    },
    {
        type:"bags",
        img:"/assets/images/slider/bags/8.jpg"
    },
    {
        type:"flower",
        img:"/assets/images/flower/blog/insta/1.jpg"
    },
    {
        type:"flower",
        img:"/assets/images/flower/blog/insta/2.jpg"
    },
    {
        type:"flower",
        img:"/assets/images/flower/blog/insta/3.jpg"
    },
    {
        type:"flower",
        img:"/assets/images/flower/blog/insta/4.jpg"
    },
    {
        type:"flower",
        img:"/assets/images/flower/blog/insta/5.jpg"
    },
    {
        type:"flower",
        img:"/assets/images/flower/blog/insta/6.jpg"
    },
    {
        type:"flower",
        img:"/assets/images/flower/blog/insta/7.jpg"
    },
    {
        type:"watch",
        img:"/assets/images/slider/watches/1.jpg"
    },
    {
        type:"watch",
        img:"/assets/images/slider/watches/2.jpg"
    },
    {
        type:"watch",
        img:"/assets/images/slider/watches/3.jpg"
    },
    {
        type:"watch",
        img:"/assets/images/slider/watches/4.jpg"
    },
    {
        type:"watch",
        img:"/assets/images/slider/watches/5.jpg"
    },
    {
        type:"watch",
        img:"/assets/images/slider/watches/6.jpg"
    },
    {
        type:"watch",
        img:"/assets/images/slider/watches/7.jpg"
    },
    {
        type:"christmas",
        img:"/assets/images/christmas/slider/1.jpg"
    },
    {
        type:"christmas",
        img:"/assets/images/christmas/slider/2.jpg"
    },
    {
        type:"christmas",
        img:"/assets/images/christmas/slider/3.jpg"
    },
    {
        type:"christmas",
        img:"/assets/images/christmas/slider/4.jpg"
    },
    {
        type:"christmas",
        img:"/assets/images/christmas/slider/5.jpg"
    },
    {
        type:"christmas",
        img:"/assets/images/christmas/slider/6.jpg"
    },
    {
        type:"christmas",
        img:"/assets/images/christmas/slider/7.jpg"
    },
    {
        type:"christmas",
        img:"/assets/images/christmas/slider/8.jpg"
    },
    {
        type:"christmas",
        img:"/assets/images/christmas/slider/9.jpg"
    }
]

module.exports = InstagramData;
